version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run: npm install && npm run build
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
            at: ~/project
      - run: sudo npm install -g firebase-tools
      - run: firebase deploy --token=$FIREBASE_TOKEN --project=$FIREBASE_PROJECT --non-interactive
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
