export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_NUMBER_ITEMS_CART = 'SET_NUMBER_ITEMS_CART';
export const ADD_FROM_SESSION_TO_CART = 'ADD_FROM_SESSION_TO_CART';
export const REMOVE_AFTER_BUY = 'REMOVE_AFTER_BUY';
